### ISSUE TITLE
老哥 有动态调整字体大小并且UI样式也能跟着改变的案例吗

### ISSUE THREAD

**Issue by Wuou** [SmileZXLee/ZXTheme#4]
老哥 有动态调整字体大小并且UI样式也能跟着改变的案例吗

**Comment by SmileZXLee** [comment]
修改全局字体，或根据特定条件修改字体可以通过
```objc
[ZXTheme defaultTheme].zx_labelThemeBlock = ^ZXLabelTheme * _Nonnull(UILabel * _Nonnull label) {
    ZXLabelTheme *labelTheme = [[ZXLabelTheme alloc]init];
    labelTheme.font = [UIFont systemFontOfSize:14];
    return labelTheme;
};
```
来统一修改，“UI样式跟着改变”不知道您说的具体是什么需求呢？

**Comment by Wuou** [comment]
类似微信的调整字体大小，我们的app需要合适老年人用，所以需要放大字体。😂 在2020年10月20日 14:02，ZXLee 写道： 

修改全局字体，或根据特定条件修改字体可以通过

[ZXTheme defaultTheme].zx_labelThemeBlock = ^ZXLabelTheme * _Nonnull(UILabel * _Nonnull label) {

    ZXLabelTheme *labelTheme = [[ZXLabelTheme alloc]init];

    labelTheme.font = [UIFont systemFontOfSize:14];

    return labelTheme;

};

来统一修改，“UI样式跟着改变”不知道您说的具体是什么需求呢？



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/SmileZXLee/ZXTheme/issues/4#issuecomment-712613856",

"url": "https://github.com/SmileZXLee/ZXTheme/issues/4#issuecomment-712613856",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by SmileZXLee** [comment]
[ZXThemeDemo.zip](https://github.com/SmileZXLee/ZXTheme/files/5413471/ZXThemeDemo.zip)
您好，我增加了一个小demo，您可以点击上面的链接下载。

**Comment by Wuou** [comment]
> [ZXThemeDemo.zip](https://github.com/SmileZXLee/ZXTheme/files/5413471/ZXThemeDemo.zip)
> 您好，我增加了一个小demo，您可以点击上面的链接下载。

好的 感谢
